import sys
import re
import argparse
import urllib.parse
import requests
from datetime import datetime

# Now Python can seamlessly see and import the centralized helper utility cleanly!
from sources.agents.agent_helper import (
    write_file
)

# super agent
from sources.agents.subagent_super import AbstractSubAgent

# ==============================================================================
# GLOBAL CONFIGURATION PATHS - CONFIG HERE TO CUSTOMIZE DIRECTORY STRUCTURE
# ==============================================================================
# models list
SYSTEM_PROMPT_TEMPLATE      = "agent_estimator.prompt.system.md"
USER_PROMPT_TEMPLATE        = "agent_estimator.prompt.user.md"

EST_RAW_FILE                = "estimation.md"
EST_LOG_FILE                = "estimation_log.md"

DEFAULT_BUFFER_RATION       = 1.5

DEFAULT_EST_LANGUAGE        = "English"


class EnterpriseAutonomousProjectEstimatorAgent(AbstractSubAgent):
    def __init__(self, **kwargs):
        super().__init__(agent_id='EnterpriseAutonomousProjectEstimator', **kwargs)
    
    # @override
    def initialize(self):
        # start initialization
        super().initialize()
        self.buffer_ratio = self.get_kwargs("buffer") or DEFAULT_BUFFER_RATION
        self.language = self.get_kwargs("language") or DEFAULT_EST_LANGUAGE
    
    # @override
    def agent_log_file(self) -> str:
        return self.__output_storage_path__(storage_name="output_estimation", file=EST_LOG_FILE)
    
    # @override
    def system_prompt_template(self) -> str:
        return self.__agents_path__(storage_name="storage_estimation", file=SYSTEM_PROMPT_TEMPLATE)
    
    # @override
    def user_prompt_template(self) -> str:
        return self.__agents_path__(storage_name="storage_estimation", file=USER_PROMPT_TEMPLATE)
    
    # @override
    def pre_execute(self, **kwargs):
        # read idea
        idea_same_project, raw_idea_content = self.__read_idea_or_requirements__(ignore_not_found=True)
        self.idea_is_project = idea_same_project
        
        # no idea also no requirements
        if not raw_idea_content:
            self.logger.critical(f"💀 Not found IDEA / Requirements file to process")
            sys.exit(1)
        
        # read ba/SRS
        raw_srs_content = self.__read_srs__(ignore_not_found=False)
        
        # read sa/blueprint
        raw_blueprint_content = self.__read_blueprint__(ignore_not_found=False)
        
        # return merged new values
        now = datetime.now()
        return {
            **kwargs,
            "target_language": self.language,
            "idea_id": self.idea_id,
            "project_name": self.__current_project_name__() or "-",
            "project_description": self.__current_project_description__() or "-",
            "current_timestamp": now.strftime("%Y/%m/%d %H:%M:%S"),
            "current_timestamp_2": now.strftime("%Y%m%d%H%M%S"),
            "buffer_ratio": self.buffer_ratio,
            "raw_idea_content": raw_idea_content,
            "raw_srs_content": raw_srs_content,
            "raw_blueprint_content": raw_blueprint_content
        }
    
    # @override
    def clean_response(self, raw_response, **kwargs):
        # Non-greedy regex mapping to sweep all markdown blocks bounded by mermaid tags
        mermaid_blocks = re.findall(r'```mermaid\s*(.*?)\s*```', raw_response, re.DOTALL)
        if not mermaid_blocks:
            self.logger.warn("Zero functional mermaid visualization blocks detected inside the markdown body.")
        
        # Explicit fallback architectural name arrays
        chart_names = ["cost_chart.svg", "timeline_chart.svg", "risk_matrix.svg"]
        self.logger.info(f"[ 📊 MERMAID ENGINE ] Intercepted {len(mermaid_blocks)} dynamic diagrams. Running vector compilation pipeline...")
        visualizations_data = {}
        
        for idx, code in enumerate(mermaid_blocks):
            clean_code = code.strip()
            
            # URL-encode the raw code content safe string character array payloads
            encoded_code = urllib.parse.quote(clean_code)
            render_url = f"https://mermaid.ink{encoded_code}"
            
            # Polymorphic file naming boundaries to protect extra diagrams generated by AI
            file_name = chart_names[idx] if idx < len(chart_names) else f"custom_governance_chart_{idx}.svg"
            
            self.logger.info(f"⏳ Querying dynamic vector graph data for layout file: {file_name}...")
            try:
                img_response = requests.get(render_url, timeout=20)
                if img_response.status_code == 200 and b"<svg" in img_response.content:
                    visualizations_data = {
                        **visualizations_data,
                        file_name: img_response.content.strip()
                    }
                    self.logger.info(f"💾 Highly-scalable vector graphic successfully extracted at index: {idx}")
                else:
                    self.logger.warn(f"⚠️ Render pipeline returned invalid metadata block structure at index: {idx}")
            except Exception as net_err:
                self.logger.warn(f"⚠️ Network exception or latency spike during chart extraction: {str(net_err)}")
        
        return visualizations_data
    
    # @override
    def process_communication(self, **kwargs):
        response_data = self.get_kwargs_by_key(key="raw_response", **kwargs)
        if not response_data:
            raise RuntimeError("❌ Invalid AI raw response.")
        
        # export estimation as md files
        write_file(
            file=self.__storage_path__("storage_estimation", file=f"{self.project_name}/enterprise-estimation.md"),
            data=response_data
        )
        
        # write output file
        write_file(
            file=self.__output_storage_path__(storage_name="output_estimation", file=EST_RAW_FILE),
            data=response_data
        )
        
        # export visualizations
        visualizations = self.get_kwargs_by_key(key="clean_response", **kwargs)
        if visualizations:
            for file, data in visualizations.items():
                write_file(
                    file=self.__storage_path__("storage_estimation", file=f"{self.project_name}/visualizations/{file}"),
                    data=data
                )

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--idea", type=str, help="Idea Identity / Project Name for searching")
    parser.add_argument("--buffer-ratio", type=float, default=1.5, help="Estimation with buffer ratio. Ex: 1.5")
    parser.add_argument("--language", type=str, help="Translate Estimation to language. Ex: Vietnamese, English, etc.")
    args = parser.parse_args()
    EnterpriseAutonomousProjectEstimatorAgent(
        idea=args.idea,
        project=args.idea,
        language=args.language,
        buffer=args.buffer_ratio
    ).execute()
